version: 2
jobs:
  build:
    docker:
      - image: node:11.10.1
      - image: circleci/postgres:11-alpine-ram
    working_directory: ~/repo

    steps:
      - checkout:
          post:
            - git fetch --all

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run: yarn install

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      # Eslint
      - run: yarn lint
